name: supabase

services:

  studio:
    container_name: supabase-studio
    image: supabase/studio:2026.03.16-sha-5528817
    restart: unless-stopped
    depends_on:
      meta:
        condition: service_started
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      SUPABASE_URL: http://kong:8000
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  kong:
    container_name: supabase-kong
    image: kong/kong:3.9.1
    restart: unless-stopped
    depends_on:
      - auth
      - rest
    ports:
      - "8000:8000"
      - "8443:8443"
    env_file: .env
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
    volumes:
      - ./volumes/api/kong.yml:/usr/local/kong/kong.yml

  auth:
    container_name: supabase-auth
    image: supabase/gotrue:v2.186.0
    restart: unless-stopped
    depends_on:
      - db
    env_file: .env
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      GOTRUE_DB_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      GOTRUE_SITE_URL: ${SITE_URL}
      GOTRUE_JWT_SECRET: ${JWT_SECRET}
      GOTRUE_EXTERNAL_EMAIL_ENABLED: ${ENABLE_EMAIL_SIGNUP}
      GOTRUE_MAILER_AUTOCONFIRM: ${ENABLE_EMAIL_AUTOCONFIRM}
      API_EXTERNAL_URL: ${API_EXTERNAL_URL}
      GOTRUE_JWT_EXP: ${JWT_EXPIRY}
      GOTRUE_DB_MAX_POOL_SIZE: ${POOLER_DEFAULT_POOL_SIZE}

  rest:
    container_name: supabase-rest
    image: postgrest/postgrest:v14.6
    restart: unless-stopped
    depends_on:
      - db
    env_file: .env
    environment:
      PGRST_DB_URI: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}

  realtime:
    container_name: realtime-dev.supabase-realtime
    image: supabase/realtime:v2.76.5
    restart: unless-stopped
    depends_on:
      - db
    env_file: .env

  storage:
    container_name: supabase-storage
    image: supabase/storage-api:v1.44.2
    restart: unless-stopped
    depends_on:
      - db
      - rest
    env_file: .env
    environment:
      ANON_KEY: ${ANON_KEY}
      SERVICE_KEY: ${SERVICE_ROLE_KEY}
      PGRST_JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      POSTGREST_URL: http://rest:3000
      PGRST_SCHEMA: storage
      HTTP_PORT: 5000
      STORAGE_BACKEND: file
      FILE_STORAGE_BACKEND_PATH: /var/lib/storage
    volumes:
      - ./volumes/storage:/var/lib/storage

  imgproxy:
    container_name: supabase-imgproxy
    image: darthsim/imgproxy:v3.30.1
    restart: unless-stopped

  meta:
    container_name: supabase-meta
    image: supabase/postgres-meta:v0.95.2
    restart: unless-stopped
    depends_on:
      - db
    env_file: .env

  functions:
    container_name: supabase-edge-functions
    image: supabase/edge-runtime:v1.71.2
    restart: unless-stopped
    env_file: .env

  db:
    container_name: supabase-db
    image: supabase/postgres:15.8.1.085
    restart: unless-stopped
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  vector:
    container_name: supabase-vector
    image: timberio/vector:0.53.0-alpine
    restart: unless-stopped
    env_file: .env

  supavisor:
    container_name: supabase-pooler
    image: supabase/supavisor:2.7.4
    restart: unless-stopped
    depends_on:
      - db
    env_file: .env
    ports:
      - "6543:6543"
      - "5432:5432"
    environment:
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      PORT: 6543
      POOLER_TENANT_ID: ${POOLER_TENANT_ID}
      POOLER_DEFAULT_POOL_SIZE: ${POOLER_DEFAULT_POOL_SIZE}
      POOLER_MAX_CLIENT_CONN: ${POOLER_MAX_CLIENT_CONN}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./volumes/pooler/pooler.exs:/etc/pooler/pooler.exs

volumes:
  db-config:
  deno-cache:
