name: supabase

services:

  studio:
    container_name: supabase-studio
    image: supabase/studio:2026.03.16-sha-5528817
    restart: unless-stopped
    depends_on:
      meta:
        condition: service_started
    ports:
      - "3000:3000"
    environment:
      SUPABASE_URL: http://kong:8000
      SUPABASE_PUBLIC_URL: ${SUPABASE_PUBLIC_URL}
      SUPABASE_ANON_KEY: ${ANON_KEY}
      SUPABASE_SERVICE_KEY: ${SERVICE_ROLE_KEY}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  kong:
    container_name: supabase-kong
    image: kong/kong:3.9.1
    restart: unless-stopped
    depends_on:
      - auth
      - rest
    ports:
      - "8000:8000"
      - "8443:8443"
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout

  auth:
    container_name: supabase-auth
    image: supabase/gotrue:v2.186.0
    restart: unless-stopped
    depends_on:
      - db
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      GOTRUE_DB_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      GOTRUE_SITE_URL: http://localhost:3000
      GOTRUE_JWT_SECRET: ${JWT_SECRET}

  rest:
    container_name: supabase-rest
    image: postgrest/postgrest:v14.6
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PGRST_DB_URI: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}

  realtime:
    container_name: realtime-dev.supabase-realtime
    image: supabase/realtime:v2.76.5
    restart: unless-stopped
    depends_on:
      - db

  storage:
    container_name: supabase-storage
    image: supabase/storage-api:v1.44.2
    restart: unless-stopped
    depends_on:
      - db

  imgproxy:
    container_name: supabase-imgproxy
    image: darthsim/imgproxy:v3.30.1
    restart: unless-stopped

  meta:
    container_name: supabase-meta
    image: supabase/postgres-meta:v0.95.2
    restart: unless-stopped
    depends_on:
      - db

  functions:
    container_name: supabase-edge-functions
    image: supabase/edge-runtime:v1.71.2
    restart: unless-stopped

  db:
    container_name: supabase-db
    image: supabase/postgres:15.8.1.085
    restart: unless-stopped
    ports:
      - "5432:5432" # 🔥 THIS FIXES YOUR ISSUE
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  vector:
    container_name: supabase-vector
    image: timberio/vector:0.53.0-alpine
    restart: unless-stopped

  supavisor:
    container_name: supabase-pooler
    image: supabase/supavisor:2.7.4
    restart: unless-stopped

volumes:
  db-config:
  deno-cache:
