from __future__ import annotations

import io
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel
from weasyprint import HTML
from jinja2 import Template

from app.database import get_pool
from app.routers.auth import get_current_user
from app.utils.supabase import supabase_client
from app.config import settings
from app.utils.logging import get_logger

logger = get_logger(__name__)

router = APIRouter(prefix="/reports", tags=["reports"])


class ReportResponse(BaseModel):
    report_url: str


# --- Minimal Jinja HTML Template for the Report ---
REPORT_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>SquintScale Report</title>
    <style>
        @page {
            size: A4;
            margin: 2cm;
            @bottom-center {
                content: "Generated by SquintScale | " "Page " counter(page);
                font-family: sans-serif;
                font-size: 9pt;
                color: #888;
            }
        }
        body { font-family: sans-serif; color: #333; line-height: 1.5; }
        h1 { color: #111; border-bottom: 2px solid #eee; padding-bottom: 0.5rem; }
        .score-block { text-align: center; margin: 2rem 0; padding: 2rem; background: #f8f9fa; border-radius: 8px; }
        .score-number { font-size: 4rem; font-weight: bold; margin: 0; }
        .score-band { font-size: 1.5rem; font-weight: bold; text-transform: uppercase; margin-top: 0.5rem; }
        .details { margin-bottom: 2rem; color: #555; }
        
        table { width: 100%; border-collapse: collapse; margin: 2rem 0; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
        th { background-color: #f1f3f5; }
        
        .images { display: flex; justify-content: space-between; gap: 1rem; margin-top: 2rem; }
        .images div { width: 48%; }
        .images img { width: 100%; border: 1px solid #ccc; border-radius: 4px; }
        .images p { text-align: center; font-weight: bold; margin-bottom: 0.5rem; }

        .suggestions { margin-top: 3rem; }
        .suggestion-item { padding: 1rem; border-left: 4px solid #0066cc; background: #f8f9fa; margin-bottom: 1rem; }
        .severity { font-size: 0.8rem; font-weight: bold; text-transform: uppercase; padding: 2px 6px; background: #e0e0e0; border-radius: 3px; margin-right: 8px; }
        .critical { background: #fee2e2; color: #dc2626; border-left-color: #dc2626; }
        .high { background: #ffedd5; color: #ea580c; border-left-color: #ea580c; }
        .medium { background: #fef9c3; color: #ca8a04; border-left-color: #ca8a04; }
    </style>
</head>
<body>
    <h1>Accessibility Vision Report</h1>
    
    <div class="details">
        <strong>Source:</strong> {{ analysis.input_url or analysis.original_image_path }}<br>
        <strong>Analyzed on:</strong> {{ analysis.created_at.strftime('%Y-%m-%d %H:%M') if analysis.created_at else 'N/A' }}
    </div>

    <div class="score-block">
        <p class="score-number">{{ analysis.squint_score or 'N/A' }}</p>
        <p class="score-band">Band {{ analysis.squint_band or 'N/A' }}</p>
    </div>

    <h2>Dimension Breakdown</h2>
    <table>
        <thead>
            <tr>
                <th>Dimension</th>
                <th>Score</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Contrast</td>
                <td>{{ "%.1f"|format(metrics.contrast_score) if metrics and metrics.contrast_score else 'N/A' }}</td>
                <td>{{ 'Pass' if metrics and metrics.contrast_score >= 80 else 'Review' }}</td>
            </tr>
            <tr>
                <td>Font Size</td>
                <td>{{ "%.1f"|format(metrics.font_size_score) if metrics and metrics.font_size_score else 'N/A' }}</td>
                <td>{{ 'Pass' if metrics and metrics.font_size_score >= 80 else 'Review' }}</td>
            </tr>
            <tr>
                <td>Visual Clutter</td>
                <td>{{ "%.1f"|format(metrics.visual_clutter_score) if metrics and metrics.visual_clutter_score else 'N/A' }}</td>
                <td>{{ 'Pass' if metrics and metrics.visual_clutter_score >= 70 else 'Review' }}</td>
            </tr>
             <tr>
                <td>Color Accessibility</td>
                <td>{{ "%.1f"|format(metrics.color_accessibility_score) if metrics and metrics.color_accessibility_score else 'N/A' }}</td>
                <td>{{ 'Pass' if metrics and metrics.color_accessibility_score >= 80 else 'Review' }}</td>
            </tr>
        </tbody>
    </table>

    <div class="images">
        <div>
            <p>Original Capture</p>
            {% if original_url %}
            <img src="{{ original_url }}" alt="Original image">
            {% else %}
            <div style="border:1px dashed #ccc; padding: 2rem; text-align: center;">Original Image Unavailable</div>
            {% endif %}
        </div>
        <div>
            <p>Neural Degraded Simulation</p>
            {% if degraded_url %}
            <img src="{{ degraded_url }}" alt="Degraded image">
            {% else %}
            <div style="border:1px dashed #ccc; padding: 2rem; text-align: center;">Simulation Unavailable</div>
            {% endif %}
        </div>
    </div>

    {% if suggestions %}
    <div class="suggestions">
        <h2>Recommendations</h2>
        {% for s in suggestions %}
        <div class="suggestion-item {{ s.severity.lower() }}">
            <div>
                <span class="severity">{{ s.severity }}</span>
                <strong>+{{ "%.1f"|format(s.expected_lift) }} Lift</strong>
            </div>
            <p style="margin-top: 0.5rem; margin-bottom: 0;">{{ s.suggestion }}</p>
        </div>
        {% endfor %}
    </div>
    {% endif %}

    <p style="margin-top: 4rem; text-align: center; color: #888; font-size: 0.9em;">
        Generated internally by SquintScale PDF Engine.
    </p>
</body>
</html>
"""


@router.post("/{analysis_id}", response_model=ReportResponse, status_code=status.HTTP_201_CREATED)
async def generate_report(
    analysis_id: UUID,
    user_id: UUID = Depends(get_current_user),
):
    """
    Generate a PDF report for an analysis using WeasyPrint.
    Compiles the DB records into HTML -> PDF, uploads it, and saves the reference.
    """
    pool = get_pool()
    async with pool.acquire() as conn:
        # 1. Fetch analysis to ensure it exists and belongs to user
        analysis = await conn.fetchrow(
            "SELECT * FROM public.analyses WHERE id = $1 AND user_id = $2",
            analysis_id,
            user_id,
        )
        if not analysis:
            raise HTTPException(status_code=404, detail="Analysis not found")
        
        if analysis["status"] != "completed":
            raise HTTPException(
                status_code=400, 
                detail=f"Cannot generate report for analysis in '{analysis['status']}' state"
            )

        # 2. Fetch metrics
        metrics = await conn.fetchrow(
            "SELECT * FROM public.analysis_metrics WHERE analysis_id = $1",
            analysis_id,
        )
        
        # 3. Fetch suggestions
        suggestions = await conn.fetch(
            "SELECT * FROM public.suggestions WHERE analysis_id = $1 ORDER BY expected_lift DESC",
            analysis_id,
        )

        storage_path = f"{user_id}/reports/{analysis_id}.pdf"

        # Check if report already exists in DB so we don't regenerate forever
        existing = await conn.fetchrow(
            "SELECT storage_path FROM public.reports WHERE analysis_id = $1",
            analysis_id
        )

        if not existing:
            try:
                # 4. Gather image URLs using the backend Service Key
                bucket = supabase_client.storage.from_(settings.storage_bucket)
                
                original_url = None
                degraded_url = None
                
                if analysis["original_image_path"]:
                    original_url = bucket.get_public_url(analysis["original_image_path"])
                if analysis["degraded_image_path"]:
                    degraded_url = bucket.get_public_url(analysis["degraded_image_path"])

                # 5. Render HTML
                template = Template(REPORT_TEMPLATE)
                html_content = template.render(
                    analysis=dict(analysis),
                    metrics=dict(metrics) if metrics else None,
                    suggestions=[dict(s) for s in suggestions],
                    original_url=original_url,
                    degraded_url=degraded_url,
                )

                # 6. Generate PDF buffer sync blocking is fine for MVP reports or could offload to threadpool
                pdf_bytes = HTML(string=html_content).write_pdf()

                # 7. Upload to Supabase
                logger.info(f"Uploading PDF report to {storage_path}")
                bucket.upload(
                    path=storage_path,
                    file=pdf_bytes,
                    file_options={"content-type": "application/pdf", "upsert": "true"},
                )

                # 8. Insert into reports table
                await conn.execute(
                    """
                    INSERT INTO public.reports (analysis_id, user_id, storage_path)
                    VALUES ($1, $2, $3)
                    ON CONFLICT (analysis_id) DO UPDATE SET storage_path = EXCLUDED.storage_path
                    """,
                    analysis_id,
                    user_id,
                    storage_path
                )
            except Exception as e:
                logger.error(f"Failed to generate/upload PDF: {e}", exc_info=True)
                raise HTTPException(status_code=500, detail="Failed to generate PDF report")

    # 9. Generate Signed URL valid for 24 hours
    try:
        url_res = supabase_client.storage.from_(settings.storage_bucket).create_signed_url(
            storage_path, 
            expires_in=86400  # 24h
        )
        signed_url = url_res.get("signedURL")
        if not signed_url:
            raise ValueError("No signedURL returned by Supabase")
        return ReportResponse(report_url=signed_url)
    except Exception as e:
        logger.error(f"Failed to generate signed URL for {storage_path}: {e}")
         # fallback to public url string manipulation if bucket happens to be fully public
         # but reports should probably be tight
        raise HTTPException(status_code=500, detail="Failed to generate secure URL for report")


@router.get("/{analysis_id}", response_model=ReportResponse)
async def get_report(
    analysis_id: UUID,
    user_id: UUID = Depends(get_current_user),
):
    """
    Fetch the signed URL for an existing generated report.
    Returns 404 if it hasn't been generated yet.
    """
    pool = get_pool()
    async with pool.acquire() as conn:
        row = await conn.fetchrow(
            "SELECT storage_path FROM public.reports WHERE analysis_id = $1 AND user_id = $2",
            analysis_id,
            user_id,
        )
        
    if not row:
        raise HTTPException(status_code=404, detail="Report not yet generated")

    storage_path = row["storage_path"]
    
    try:
        url_res = supabase_client.storage.from_(settings.storage_bucket).create_signed_url(
            storage_path, 
            expires_in=86400
        )
        signed_url = url_res.get("signedURL")
        if not signed_url:
            raise ValueError("No signedURL returned")
        return ReportResponse(report_url=signed_url)
    except Exception as e:
        logger.error(f"Failed to generate signed URL for existing report: {e}")
        raise HTTPException(status_code=500, detail="Failed to generate secure URL for report")
